INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (200,  '2015-01-01', 'snack', 'snack', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (400,  '2015-01-02', 'lunch', 'lunch', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (650,  '2015-01-04', 'supermarket', 'supermarket', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (100,  '2015-02-01', 'bike repair', 'bike repair', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (1200, '2015-02-08', 'lunch', 'lunch', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (200,  '2015-02-07', 'dinner', 'dinner', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (300,  '2015-02-01', 'supermarket', 'supermarket', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (400,  '2015-02-06', 'lunch', 'lunch', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (500,  '2015-02-01', 'underground passage', 'underground passage', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (600,  '2015-03-08', 'bike repair', 'bike repair', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (700,  '2015-03-01', 'supermarket', 'supermarket', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (800,  '2015-03-09', 'payment power', 'payment power', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (900,  '2015-03-01', 'dinner', 'dinner', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (1000, '2015-03-04', 'lunch', 'lunch', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (1200, '2015-03-06', 'bike repair', 'bike repair', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (1300, '2015-03-05', 'snack', 'snack', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (20,   '2015-03-06', 'underground passage', 'underground passage', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (40,   '2015-04-07', 'supermarket', 'supermarket', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (60,   '2015-04-11', 'lunch', 'lunch', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (70,   '2015-04-21', 'buy clothes', 'buy clothes', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (80,   '2015-04-11', 'dinner', 'dinner', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (90,   '2015-04-02', 'payment power', 'payment power', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (15,   '2015-05-03', 'supermarket', 'supermarket', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (25,   '2015-05-04', 'snack', 'snack', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (100,  '2015-05-25', 'lunch', 'lunch', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (200,  '2015-05-12', 'underground passage', 'underground passage', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (300,  '2015-05-15', 'dinner', 'dinner', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (400,  '2015-05-20', 'snack', 'snack', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (500,  '2015-06-30', 'supermarket', 'supermarket', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (600,  '2015-06-01', 'buy clothes', 'buy clothes', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (700,  '2015-06-11', 'lunch', 'lunch', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (800,  '2015-06-21', 'snack', 'snack', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (900,  '2015-06-01', 'dinner', 'dinner', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (21,   '2015-07-05', 'supermarket', 'supermarket', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (22,   '2015-07-09', 'underground passage', 'underground passage', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (23,   '2015-07-15', 'lunch', 'lunch', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (24,   '2015-07-20', 'snack', 'snack', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (125,  '2015-08-30', 'bike repair', 'bike repair', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (226,  '2015-08-05', 'supermarket', 'supermarket', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (2000, '2015-08-09', 'lunch', 'lunch', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (201,  '2015-08-10', 'payment power', 'payment power', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (320,  '2015-08-15', 'dinner', 'dinner', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (10,   '2015-08-21', 'buy clothes', 'buy clothes', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (240,  '2015-08-10', 'bike repair', 'bike repair', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (520,  '2015-09-01', 'supermarket', 'supermarket', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (920,  '2015-09-05', 'snack', 'snack', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (1220, '2015-09-02', 'underground passage', 'underground passage', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (220,  '2015-09-30', 'dinner', 'dinner', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (20,   '2015-10-25', 'supermarket', 'supermarket', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (220,  '2015-10-20', 'lunch', 'lunch', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (21,   '2015-11-15', 'supermarket', 'supermarket', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (20,   '2015-11-10', 'snack', 'snack', 0);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (23,   '2015-12-05', 'supermarket', 'supermarket', 1);
INSERT INTO purchases (total_value, purchase_date, description, comments, bankline) VALUES (29,   '2015-12-04', 'buy clothes', 'buy clothes', 1);
